AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless

  Sample SAM Template for serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Runtime: nodejs14.x

Parameters:
  AppEnv:
    Type: String
    Default: dev
    Description: Application environment

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RestApiId: !Ref RestApiGateway
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/app.ts

  FormHanlderFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.formHandler
      Events:
        GetForm:
          Type: Api
          Properties:
            Path: /form
            Method: get
        SubmitForm:
          Type: Api
          Properties:
            Path: /form
            Method: post
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
         - src/app.ts

  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref AppEnv
      Auth:
        ApiKeyRequired: false
        DefaultAuthorizer: RestApiAuthorizer
        Authorizers:
          RestApiAuthorizer:
            FunctionArn: !GetAtt RestApiLambdaAuthorizer.Arn
            # FunctionInvokeRole: !GetAtt RestApiLambdaAuthorizerRole.Arn
            Identity:
              Headers:
                - Authorization

  RestApiLambdaAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: auth.restApiAuthorizationHandler
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - src/auth.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${AppEnv}/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
