AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  layer-example

  Sample SAM Template for layer-example

Globals:
  Function:
    Timeout: 3
    Tracing: Active
